<?php 

//DO NOT EDIT THIS FILE. IT WOULD NOT TAKE ANY EFFECT ON SETTINGS.

$SETTINGS['iptv']['devicelog']['int'] = 25;
$SETTINGS['iptv']['streamlogs']['int'] = 0;
$SETTINGS['iptv']['vodlogs']['int'] = 0;
$SETTINGS['iptv']['ondemand_opt']['txt']= '';
$SETTINGS['iptv']['devicelog'] = 25;
$SETTINGS['iptv']['streamlogs'] = 0;
$SETTINGS['iptv']['vodlogs'] = 0;
$SETTINGS['iptv']['ondemand_opt'] = '';
$SETTINGS['iptv']['iptv.streamlogs']['int'] = 1;


$__SETTINGS['iptv.streamsstartup'] = true;
$__SETTINGS['iptv.epglength'] = '48';

//STB
$__SETTINGS['iptv.stb_theme'] = 'default';
$__SETTINGS['iptv.stb_force_theme'] = '0';
$__SETTINGS['iptv.stb_locale'] = 'en_GB.utf8';        //THIS IS ALSO USE FOR LANGUAGE IN STB.
$__SETTINGS['iptv.stb_play_by_ok'] = '1';


//RESELLERS
$__SETTINGS['iptv.user_set_account_username'] = true;
$__SETTINGS['iptv.user_set_account_password'] = false;

//ACCOUNT
$__SETTINGS['iptv.user_refund_hours'] = 0;

//TMDB
$__SETTINGS['iptv.videos.tmdb_lang'] = 'en';